
format = """
$character
"""
scan_timeout = 200
continuation_prompt = '▶▶ '

right_format = """$all"""

#[time]
#disabled = false
#time_format = "%H:%M"
#style = "bg:#1d2230"
#format = '[[ $time ](fg:#a0a9cb bg:#1d2230)]($style)' 

[aws]
symbol = "  "

[buf]
symbol = " "

[bun]
symbol = " "
format = '[$symbol $version]($style)'

[c]
symbol = " "
format = '[$symbol $version]($style) '

[cpp]
symbol = " "
format = '[$symbol $version]($style)'

[cmake]
symbol = " "
format = '[$symbol $version]($style)'


[conda]
symbol = " "
format = '[$symbol $version]($style)'


[crystal]
symbol = " "
format = '[$symbol $version]($style)'


[dart]
symbol = " "
format = '[$symbol $version]($style)'


[deno]
symbol = " "
format = '[$symbol $version]($style)'


[directory]
read_only = " 󰌾"
format = "[ $path ]($style)"

[directory.substitutions]
"/archives" = "󰈙 "
"/Downloads" = " "
"/models" = "󰙨 "
"/templates" = "📎"
"/images" = "🖼️ " 
"/recordings" = "🎥 "
"~" = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = "󰊢 "

[gcloud]
symbol = "  "

[git_branch]
symbol = "󰊢 "
format = """
[](fg:#ffb86c)\
[$symbol$branch](fg:#1a1b26 bg:#ffb86c)
[ ](fg:#ffb86c)\
"""
truncation_length = 7
truncation_symbol = ''
disabled = false

[git_commit]
commit_hash_length = 4
tag_symbol = '🕸️ '

[git_state]
format = '[\($state( $progress_current of $progress_total)\)](green) '
cherry_pick = '[ PICKING](bold orange) '

[git_metrics]
format = '[$added](fg:#c9d1d9)[ ](fg:#50fa7b)/[ $deleted](fg:#c9d1d9)[](fg:#ff5555) '
disabled = false

[git_status]
conflicted = ' 🏳 '
ahead = '  ${count} '
diverged = ' ⇕⇡ ${ahead_count}   ${behind_count} '
behind =  ' 😰 '
up_to_date = ' '
untracked = ' 󱀶 '
stashed = ' 📦 '
modified = ' 📝 '
staged = ' 󰷫 ${count} '
renamed = '   '
deleted = ' 🗑 '
format = """[$all_status$ahead_behind ](fg:#bd93f9)"""

[golang]
symbol = " "
format = '[$symbol $version]($style)'


[guix_shell]
symbol = " "
format = '[$symbol $version]($style)'


[haskell]
symbol = " "
format = '[$symbol $version]($style)'


[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "
format = '[](orange) [$version]($style) '

[julia]
symbol = " "
format = '[$symbol $version]($style)'


[kotlin]
symbol = " "
format = '[$symbol $version]($style)'


[lua]
symbol = " "
format = '[$symbol $version]($style)'


[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "
format = '[$symbol $version]($style)'


[nim]
symbol = "󰆥 "
format = '[$symbol $version]($style)'


[nix_shell]
symbol = " "
format = '[$symbol $version]($style)'


[nodejs]
symbol = " "
format = '[$symbol $version]($style)'


[ocaml]
symbol = " "
format = '[$symbol $version]($style)'


[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "
format = '[$symbol $version]($style)'

[php]
symbol = " "
format = '[$symbol $version]($style)'

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[python]
symbol = " "
format = '[$symbol $version]($style)'

[rlang]
symbol = "󰟔 "
format = '[$symbol $version]($style)'

[ruby]
symbol = " "
format = '[$symbol $version]($style)'

[rust]
symbol = "󱘗 "
format = '[$symbol $version]($style)'

[scala]
symbol = " "
format = '[$symbol $version]($style)'

[swift]
symbol = " "
format = '[$symbol $version]($style)'

[zig]
symbol = " "
format = '[$symbol $version]($style)'

[battery]
full_symbol = '🔋 '
charging_symbol = '⚡️ '
discharging_symbol = '💀 '

[[battery.display]]
threshold = 15
style = 'bold red'

[[battery.display]]
threshold = 30
style = 'bold yellow'
discharging_symbol = '  '

[gradle]
symbol = " "

[character] 
error_symbol = """[❌ ](bold red)"""
success_symbol = """[🐏](bold green)""" 


